### ISSUE TITLE
Build broken on linux

### ISSUE THREAD

**Issue by ebachard** [Yurter/FFmpeg.cpp#1]
Hi,

I tried to build your code (very interesting), but it's frankly unbuildable : some ctors are missing, or using undefined types, and other issues. Does it really build for you without warnings ? 

e.g.:

````
./fpp/core/Logger.hpp:35:31: error: ‘string_view’ in namespace ‘std’ does not name a type
         void print(const std::string_view caller_name, LogLevel log_level, Args&&... args) const {
                               ^~~~~~~~~~~
./fpp/core/Logger.hpp:73:46: error: ‘string_view’ in namespace ‘std’ does not name a type
         std::string formatMessage(const std::string_view caller_name, LogLevel log_level, Args&&... args) const {
                                              ^~~~~~~~~~~
./fpp/core/Logger.hpp:91:14: error: ‘string_view’ in namespace ‘std’ does not name a type
         std::string_view    logLevelToString(LogLevel value) const;
              ^~~~~~~~~~~

````
Changing for C++17, I got the first issues half fixed (zillions of warnings) and the next is: 

````
          ^~~~~~~~~~~~~~
./fpp/refi/RescaleContext.hpp:16:9: error: ‘fpp::RescaleContext::RescaleContext(fpp::IOParams)’, declared using unnamed type, is used but never defined [-fpermissive]
         RescaleContext(IOParams parameters);
         ^~~~~~~~~~~~~~
In file included from ./fpp/stream/VideoParameters.hpp:2,
                 from ./fpp/stream/Stream.hpp:2,
                 from ./fpp/base/FormatContext.hpp:5,
                 from ./fpp/context/InputFormatContext.hpp:2,
                 from examples/filter_timelapase.cpp:3:
./fpp/base/Parameters.hpp:19:67: note: ‘using IOParams = struct fpp::<unnamed>’ does not refer to the unqualified type, so it is not used for linkage
     using IOParams = struct { SpParameters in; SpParameters out; };
                                                                   ^
In file included from examples/filter_timelapase.cpp:8:
./fpp/refi/RescaleContext.hpp:16:9: warning: ‘fpp::RescaleContext::RescaleContext(fpp::IOParams)’ used but never defined
         RescaleContext(IOParams parameters);

````
Missing contructor ? When I add one, it appears twice ?  

I'm very used to fix a lot of issue, but I'm stuck there, because I can't retrieve what you mean in your interface. Thanks a lot for any advice, and thanks fr sharing your code, I discovered another approach with ffmpeg and cpp

**Comment by Yurter** [comment]
Hi,

thanks for finding the issue, I just fixed it and you can try to build master again but make sure you using ffmpeg 4+ version. I tested on Ubuntu 18.04, g++ 9.0.1 and ffmpeg 4.2.2

**Comment by ebachard** [comment]
Hello,

I still have a lot of warnings, but the build is OK and I can study your code and progress :-)
Thank you very much for your reactivity !   

BTW : what is the license of your code ? Maybe I didn't search well, but I couldn't find any.

**Comment by Yurter** [comment]
I added LGPL-2.1 license
